// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb_xLj_ACYvJ7EQklzAMrtfkuUU11_wRI',
    appId: '1:65979687355:web:51dabe27bdb4a36921e49e',
    messagingSenderId: '65979687355',
    projectId: 'airqo-a4232',
    authDomain: 'airqo-a4232.firebaseapp.com',
    storageBucket: 'airqo-a4232.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf9NaFnK90JHeeiXDfVC_Cyf7Uq77DzE0',
    appId: '1:65979687355:android:6169ed6a5ab78d6421e49e',
    messagingSenderId: '65979687355',
    projectId: 'airqo-a4232',
    storageBucket: 'airqo-a4232.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDPaAhwLIpvwHd-IPer5No6xvHp6ilSl0',
    appId: '1:65979687355:ios:d5cb36b192dbfc1d21e49e',
    messagingSenderId: '65979687355',
    projectId: 'airqo-a4232',
    storageBucket: 'airqo-a4232.appspot.com',
    iosBundleId: 'com.example.ecomm',
  );
}
